version: '3'

services:
  nginx:
    build: ./
    image: dockerdemo
    ports:
      - 80:80
    volumes:
      - ./src:/usr/share/nginx/html
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: aws-log
