version: '3'

services:
  web:
    image: 021077554300.dkr.ecr.ap-northeast-1.amazonaws.com/rails_test:latest
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      DB_ROOT_USERNAME: root
      DB_USERNAME: development
      DB_PASSWORD: password
      TZ: Asia/Tokyo
      DB_HOST: db

  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./volumes/mysql/data/:/var/lib/mysql

  nginx:
    image: 021077554300.dkr.ecr.ap-northeast-1.amazonaws.com/nginx_test:latest
    ports:
      - "80:80"
    depends_on:
      - web
