name: Deploy to EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-1
  INSTANCE: i-024d5255bcc2e76ca

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Start SSM session
      uses: aws-actions/start-ssm-session@v1
      with:
        instance-id: ${{ env.INSTANCE }}
        region: ${{ env.AWS_REGION }}

    - name: Deploy
      run: |
        # Deploy commands here

