name: EC2 update

on:
  workflow_dispatch:

jobs:
  start-ec2:

    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
    - uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: EC2 update
      run : |
        export RESPONSE=$(aws ssm send-command --document-name "AWS-RunShellScript" --document-version "1" --targets '[{"Key":"InstanceIds","Values":["i-0278a0585c410c6d2"]}]' --parameters '{"workingDirectory":[""],"executionTimeout":["3600"],"commands":["sudo -i","cd /root","docker-compose pull","docker-compose run web rails db:migrate:reset","docker-compose run web rails db:seed:replant","docker-compose up -d"]}' --timeout-seconds 600 --max-concurrency "50" --max-errors "0" --region ap-northeast-1)
        export COMMAND_ID=$(echo $RESPONSE | jq .Command.CommandId)
        echo "commandId=${COMMAND_ID} >> $GITHUB_OUTPUT"
