name: Deploy to EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-1
  EC2_INSTANCE_ID: i-024d5255bcc2e76ca

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Execute command
      uses: debugger24/action-aws-ssm-run-command@v1
      with:
        instance-ids: ${{ env.EC2_INSTANCE_ID }}
        document-name: AWS-RunRemoteScript
        parameters: |
          {
            "commands": [
              "sudo apt-get update",
              "sudo apt-get install -y docker.io",
              "sudo curl -L https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose",
              "sudo chmod +x /usr/local/bin/docker-compose",
              "cd /path/to/your/docker-compose/project",
              "sudo docker-compose up -d"
            ],
            "executionTimeout": ["3600"]
          }
