name: Nginx

on:
  workflow_dispatch:

jobs:
  build-and-push:

    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
    - uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Nginx
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME_NGINX }}
      run: |
        docker build -t nginx_test nginx --platform linux/amd64
        docker tag nginx_test:latest 021077554300.dkr.ecr.ap-northeast-1.amazonaws.com/nginx_test:latest
        docker push 021077554300.dkr.ecr.ap-northeast-1.amazonaws.com/nginx_test:latest
