name: AWS SSM Send-Command Example

on:
  push:
    branches:
    - main

env:
  AWS_REGION: ap-northeast-1
  EC2_INSTANCE_ID: i-024d5255bcc2e76ca

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to EC2 instance using SSM
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ssm start-session --target ${{ env.EC2_INSTANCE_ID }} --region ${{ env.AWS_REGION }}
      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ env.EC2_INSTANCE_ID }}

          working-directory: /root/ec2_cicd_test

      - name: Pull the latest code from GitHub
        run: |
          sudo chown -R $USER:$USER /root/ec2_cicd_test
          cd /root/ec2_cicd_test
          git pull origin main
