name: AWS SSM Send-Command Example

on:
  push:
    branches:
    - main

env:
  AWS_REGION: ap-northeast-1
  EC2_INSTANCE_ID: i-024d5255bcc2e76ca

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ env.EC2_INSTANCE_ID }}

          working-directory: /root/ec2_cicd_test
          command: deployer.sh

      # Catch SSM outputs
      - name: step1
        run: aws ssm start-session --target i-024d5255bcc2e76ca

      - name: step2
        run: sudo su --login root

      - name: step3
        run: cd /root/ec2_cicd_test

      - name: step4
        run: git pull
