name: get-rails-log

on:
  schedule:
    - cron: '*/10 * * * *' # 10分ごとに実行

jobs:
  build:

    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
    - uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: get rails-log
      run: |
        export RESPONSE=$(aws ssm send-command --document-name "AWS-RunShellScript" --document-version "1" --targets '[{"Key":"InstanceIds","Values":["i-0278a0585c410c6d2"]}]' --parameters '{"commands":["sudo -i","cd /root","aws s3 cp /var/lib/docker/volumes/root_log/_data/puma.stdout.log s3://rails-log-puma/$(date +\"%Y-%m-%d-%H-%M-%S\").txt","truncate -s 0 /var/lib/docker/volumes/root_log/_data/puma.stdout.log"],"workingDirectory":[""],"executionTimeout":["3600"]}' --timeout-seconds 600 --max-concurrency "50" --max-errors "0" --region ap-northeast-1)
        export COMMAND_ID=$(echo $RESPONSE | jq .Command.CommandId)
        echo "commandId=${COMMAND_ID} >> $GITHUB_OUTPUT"
